### ISSUE TITLE
Failed to start bakta annotation

### ISSUE THREAD

**Issue by UpalabdhaD** [weisberglab/beav#3]
beav --input shivanshi_bakta_annotation/Plant_Pathogen/Pectobacterium_carotovorum/Pectobacterium_carotovorum.fna  --output beav23/ --skip_tiger --bakta_arguments '--db $HOME/Shivanshi/shivanshi_bakta_annotation/db/ --force'
BEAV version 1.0.0

--input shivanshi_bakta_annotation/Plant_Pathogen/Pectobacterium_carotovorum/Pectobacterium_carotovorum.fna --output beav23/ --skip_tiger --bakta_arguments --db $HOME/Shivanshi/shivanshi_bakta_annotation/db/ --force

Checking prerequisites:
----------------------------------------------------------
Bakta: OK
antiSMASH: OK
MacSyFinder: OK
IntegronFinder: OK
DefenseFinder: OK
TIGER2: skipped
GapMind: OK
DBSCAN-SWA: OK
----------------------------------------------------------

Running Bakta

ERROR: wrong database path! --db=$HOME/Shivanshi/shivanshi_bakta_annotation/db/
Error: error occurred while running Bakta. Please see Bakta.log
Elapsed: 0hrs 0min 1sec

Done

----------------------------------------------------------

Annotation of other sequence elements

Traceback (most recent call last):
  File "/home2/upalabdha/test_beav/beav/share/beav-1.1.0/scripts/subset_cds_genbank.py", line 10, in <module>
    for record in SeqIO.parse(f"./bakta/{strain}.gbff","gb"):
  File "/home2/upalabdha/test_beav/beav/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/home2/upalabdha/test_beav/beav/lib/python3.9/site-packages/Bio/SeqIO/InsdcIO.py", line 93, in __init__
    super().__init__(source, mode="t", fmt="GenBank")
  File "/home2/upalabdha/test_beav/beav/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: './bakta/Pectobacterium_carotovorum.gbff'

Error: Failed to open target sequence database bakta/Pectobacterium_carotovorum.fna for reading

Error: Failed to open target sequence database bakta/Pectobacterium_carotovorum.fna for reading

Error: Failed to open target sequence database bakta/Pectobacterium_carotovorum.fna for reading

mv: cannot stat './Pectobacterium_carotovorum.pip_box.out': No such file or directory
mv: cannot stat './Pectobacterium_carotovorum.hrp_box.out': No such file or directory
mv: cannot stat './Pectobacterium_carotovorum.nodbox': No such file or directory
mv: cannot stat './Pectobacterium_carotovorum.ttsbox': No such file or directory
mv: cannot stat './Pectobacterium_carotovorum.dif': No such file or directory
cat: borders/Pectobacterium_carotovorum.nodbox: No such file or directory
cat: borders/Pectobacterium_carotovorum.ttsbox: No such file or directory
cat: borders/Pectobacterium_carotovorum.dif: No such file or directory

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
cat: ./bakta/Pectobacterium_carotovorum.gff3: No such file or directory
cut: ./borders/Pectobacterium_carotovorum.virbox: No such file or directory
cut: ./borders/Pectobacterium_carotovorum.trabox: No such file or directory
cut: ./borders/Pectobacterium_carotovorum.pip_box.out: No such file or directory
cut: ./borders/Pectobacterium_carotovorum.hrp_box.out: No such file or directory
Elapsed: 0hrs 0min 0sec

Done

----------------------------------------------------------

Indentifying oriT

BLAST options error: File bakta/Pectobacterium_carotovorum.fna does not exist
BLAST Database error: No alias or index file found for nucleotide database [bakta/Pectobacterium_carotovorum.fna] in search path [/home/upalabdha/Shivanshi/beav23/Pectobacterium_carotovorum::]

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
rm: cannot remove 'bakta/Pectobacterium_carotovorum.fna.ndb': No such file or directory
rm: cannot remove 'bakta/Pectobacterium_carotovorum.fna.nhr': No such file or directory
rm: cannot remove 'bakta/Pectobacterium_carotovorum.fna.nin': No such file or directory
rm: cannot remove 'bakta/Pectobacterium_carotovorum.fna.njs': No such file or directory
rm: cannot remove 'bakta/Pectobacterium_carotovorum.fna.not': No such file or directory
rm: cannot remove 'bakta/Pectobacterium_carotovorum.fna.nsq': No such file or directory
rm: cannot remove 'bakta/Pectobacterium_carotovorum.fna.ntf': No such file or directory
rm: cannot remove 'bakta/Pectobacterium_carotovorum.fna.nto': No such file or directory
Elapsed: 0hrs 0min 0sec

Done

----------------------------------------------------------

Identifying secretion systems (MacSyFinder)

macsyfinder: "No such model definition: 'TXSScan'"
Error: error occurred while running MacSyFinder. Please see MacSyFinder.log
Elapsed: 0hrs 0min 0sec
cut: ./MacSyFinder_TXSS/best_solution.tsv: No such file or directory

Done

----------------------------------------------------------

Identifying integrons (IntegronFinder)

usage: integron_finder [-h] [--local-max] [--func-annot] [--cpu CPU]
                       [-dt DISTANCE_THRESHOLD] [--outdir OUTDIR]
                       [--union-integrases] [--cmsearch CMSEARCH]
                       [--hmmsearch HMMSEARCH] [--prodigal PRODIGAL]
                       [--path-func-annot PATH_FUNC_ANNOT] [--gembase]
                       [--gembase-path GEMBASE_PATH]
                       [--annot-parser ANNOT_PARSER] [--prot-file PROT_FILE]
                       [--attc-model ATTC_MODEL] [--evalue-attc EVALUE_ATTC]
                       [--calin-threshold CALIN_THRESHOLD]
                       [--keep-palindromes] [--no-proteins] [--promoter-attI]
                       [--max-attc-size MAX_ATTC_SIZE]
                       [--min-attc-size MIN_ATTC_SIZE] [--eagle-eyes] [--pdf]
                       [--gbk] [--keep-tmp] [--split-results]
                       [--circ | --linear] [--topology-file TOPOLOGY_FILE]
                       [--version] [--mute] [-v] [-q]
                       replicon
integron_finder: error: argument replicon: ./bakta/Pectobacterium_carotovorum.fna no such file or directory
Error: error occurred while running IntegronFinder. Please see Integron_Finder.log
Elapsed: 0hrs 0min 1sec
cut: ./Integron_Finder/Results_Integron_Finder_Pectobacterium_carotovorum/Pectobacterium_carotovorum.integrons: No such file or directory
cat: ./Integron_Finder/Results_Integron_Finder_Pectobacterium_carotovorum/Pectobacterium_carotovorum.integrons: No such file or directory

Done

----------------------------------------------------------

Identifying defense systems (DefenseFinder)

Error: error occurred while running DefenseFinder. Please see defensefinder.log
Elapsed: 0hrs 0min 0sec
cut: ./Pectobacterium_carotovorum_defense_finder_genes.tsv: No such file or directory

Done

----------------------------------------------------------

Identifying biosynthetic gene clusters (antiSMASH)

usage: antismash [-h] [options ..] sequence
antismash: error: Input file does not exist: Pectobacterium_carotovorum_cds_subset.gbk
Error: error occurred while running antiSMASH
Elapsed: 0hrs 0min 1sec
Traceback (most recent call last):
  File "/home2/upalabdha/test_beav/beav/share/beav-1.1.0/scripts/antismash_genbanks_to_table.py", line 125, in <module>
    main()
  File "/home2/upalabdha/test_beav/beav/share/beav-1.1.0/scripts/antismash_genbanks_to_table.py", line 85, in main
    df_bgcs = pd.concat(output, axis=0).sort_values(["genome_id", "contig_id", "start", "end"])
  File "/home2/upalabdha/test_beav/beav/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 274, in concat
    op = _Concatenator(
  File "/home2/upalabdha/test_beav/beav/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

Done

----------------------------------------------------------

Identifying phage (DBSCAN-SWA)

sed: can't read Pectobacterium_carotovorum_cds_subset.gbk: No such file or directory
--2024-05-23 17:13:10--  http://www.microbiome-bigdata.com/PHISDetector/static/download/DBSCAN-SWA/db.tar.gz
Connecting to 192.168.3.10:3128... connected.
Proxy request sent, awaiting response... 403 Forbidden
2024-05-23 17:13:11 ERROR 403: Forbidden.

Error: error occurred while running DBSCAN-SWA. Please see dbscan-swa.log
Elapsed: 0hrs 0min 3sec
cut: ./DBSCAN-SWA/bac_DBSCAN-SWA_prophage_summary.txt: No such file or directory

Done

----------------------------------------------------------

Characterizing amino acid biosynthesis and small carbon metabolite catabolism (GapMind)

GapMind: Running AA biosynthesis pathway analysis
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST/bin/../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST/bin/../lib/FetchAssembly.pm line 14.
BEGIN failed--compilation aborted at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST/bin/../lib/FetchAssembly.pm line 14.
Compilation failed in require at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/buildorgs.pl line 7.
BEGIN failed--compilation aborted at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/buildorgs.pl line 7.
diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 16
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: GapMind/orgs.faa
Opening the database file... 
Error opening file GapMind/orgs.faa: No such file or directory
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/gapsearch.pl line 8.
BEGIN failed--compilation aborted at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/gapsearch.pl line 8.
No such file: GapMind/aa.hits
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/gapsummary.pl line 7.
BEGIN failed--compilation aborted at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/gapsummary.pl line 7.
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/checkGapRequirements.pl line 5.
BEGIN failed--compilation aborted at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/checkGapRequirements.pl line 5.
awk: fatal: cannot open file `GapMind/aa.sum.steps' for reading: No such file or directory
GapMind: Running small molecule carbon catabolism analysis
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/gapsearch.pl line 8.
BEGIN failed--compilation aborted at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/gapsearch.pl line 8.
No such file: GapMind/carbon.hits
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/gapsummary.pl line 7.
BEGIN failed--compilation aborted at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/gapsummary.pl line 7.
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/checkGapRequirements.pl line 5.
BEGIN failed--compilation aborted at /home2/upalabdha/test_beav/beav/share/beav-1.1.0/software/PaperBLAST//bin/checkGapRequirements.pl line 5.
awk: fatal: cannot open file `GapMind/carbon.sum.steps' for reading: No such file or directory
GapMind: Done
mv: cannot stat 'formatdb.log': No such file or directory
Elapsed: 0hrs 0min 3sec

Done

----------------------------------------------------------

Identifying integrative conjugative elements [ICEs] (TIGER2)

Skipped

----------------------------------------------------------

Combining annotations and preparing final output files
Traceback (most recent call last):
  File "/home2/upalabdha/test_beav/beav/share/beav-1.1.0/scripts/combine_annotations.py", line 126, in <module>
    for record in SeqIO.parse(f"./{strain}/bakta/{strain}.gbff","gb"):
  File "/home2/upalabdha/test_beav/beav/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/home2/upalabdha/test_beav/beav/lib/python3.9/site-packages/Bio/SeqIO/InsdcIO.py", line 93, in __init__
    super().__init__(source, mode="t", fmt="GenBank")
  File "/home2/upalabdha/test_beav/beav/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: './Pectobacterium_carotovorum/bakta/Pectobacterium_carotovorum.gbff'
tee: Pectobacterium_carotovorum/logs/Beav.log: No such file or directory

Elapsed: 0hrs 0min 0sec
No such file or directory Pectobacterium_carotovorum/Pectobacterium_carotovorum_final.gbk at /home2/upalabdha/test_beav/beav/bin/bp_genbank2gff3 line 422.
cat: Pectobacterium_carotovorum/bakta/Pectobacterium_carotovorum.fna: No such file or directory

Final annotation output: Pectobacterium_carotovorum_final.gbk

----------------------------------------------------------

Creating Circos Map

ls: cannot access 'beav23//Pectobacterium_carotovorum/*_final.gbk': No such file or directory
cat: 'beav23//Pectobacterium_carotovorum/*oncogenic_plasmid_final.out.contiglist': No such file or directory
python3 beav_circos.py --input 
usage: beav_circos.py [-h] --input INPUT [--contigs [CONTIGS ...]] [--plasmid PLASMID]
beav_circos.py: error: argument --input/-i: expected one argument
Elapsed: 0hrs 0min 0sec

Done
mv: cannot stat 'Pectobacterium_carotovorum.circos.png': No such file or directory
mv: cannot stat 'Pectobacterium_carotovorum.circos.pdf': No such file or directory
mv: cannot stat 'Pectobacterium_carotovorum.oncogenes.png': No such file or directory
mv: cannot stat 'Pectobacterium_carotovorum.oncogenes.pdf': No such file or directory
mv: cannot stat 'Pectobacterium_carotovorum.oncogenic.gbk': No such file or directory

----------------------------------------------------------
Summary of annotations

Secretion_Systems      Defense_Systems Phages  Biosynthetic_gene_clusters      ICEs    Integrons
/home2/upalabdha/test_beav/beav/bin/beav: line 1064: N/A: No such file or directory
N/A   N/A      0       N/A    N/A  N/A

Small carbon catabolism pathways: 

Done

----------------------------------------------------------

The BEAV pipeline automates the use of a number of published software tools.
If you use these results in a publication, please include the following in your methods section and cite:

Jung J, Rahman A, Schiffer A, and Weisberg A. 2023. BEAV: a bacterial genome and mobile element annotation pipeline. https://github.com/weisberglab/beav

grep: beav23//Pectobacterium_carotovorum/logs/bakta.log: No such file or directory
Bakta version 
Schwengers O, Jelonek L, Dieckmann MA, et al. 2021. Bakta: rapid and standardized annotation of bacterial genomes via alignment-free sequence identification. Microb Genom 7: 000685.

EMBOSS:fuzznuc
EMBOSS: The European Molecular Biology Open Software Suite (2000) Rice,P. Longden,I. and Bleasby,A. Trends in Genetics 16, (6) pp276--277 
head: cannot open 'beav23//Pectobacterium_carotovorum/MacSyFinder_TXSS/macsyfinder.log' for reading: No such file or directory
MacSyFinder version 
Néron, Bertrand; Denise, Rémi; Coluzzi, Charles; Touchon, Marie; Rocha, Eduardo P.C.; Abby, SophieS 2023. MacSyFinder v2: Improved modelling and search engine to identify molecular systems igenomes. Peer Community Journal, Volume 3, article no. e28. DOI: 10.24072/pcjournal.250.

DBSCAN-SWA
Gan R, Zhou F, Si Y, et al. 2022. DBSCAN-SWA: An Integrated Tool for Rapid Prophage Detection and Annotation. Frontiers in Genetics 13.

DefenseFinder
Tesson F., Hervé A. , Touchon M., d’Humières C., Cury J., Bernheim A. Systematic and quantitative view of the antiviral arsenal of prokaryotes bioRx

grep: beav23//Pectobacterium_carotovorum/Integron_Finder/Results_Integron_Finder_Pectobacterium_carotovorum/integron_finder.out: No such file or directory
IntegronFinder version 
Néron B, Littner E, Haudiquet M, et al. 2022. IntegronFinder 2.0: Identification and Analysis of Integrons across Bacteria, with a Focus on Antibiotic Resistance in Klebsiella. Microorganisms 10: 700.

grep: beav23//Pectobacterium_carotovorum/antiSMASH/index.html: No such file or directory
antiSMASH version 
Kai Blin, Simon Shaw, Alexander M Kloosterman, Zach Charlop-Powers, Gilles P van Weezel, Marnix H Medema, & Tilmann Weber. 2021. Nucleic Acids Research DOI:10.1093/nar/gkab335.

GapMind
Amino acid biosynthesis:
Price MN, Deutschbauer AM, and Arkin AP. 2020. GapMind: Automated Annotation of Amino Acid Biosynthesis. mSystems 5: e00291-20.
Catabolic pathways:
Price MN, Deutschbauer AM, and Arkin AP. 2022. Filling gaps in bacterial catabolic pathways with computation and high-throughput genetics. PLOS Genetics 18(4): e1010156. DOI:10.1371/journal.pgen.1010156

**Comment by acarafat** [comment]
Thanks for reporting the issue. Can you also share the `Bakta.log`?
